"""DM-9999992

Revision ID: 8ab59bae6211
Revises: 12f0d22a2347
Create Date: 2024-12-02 20:12:51.193104+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "8ab59bae6211"
down_revision: Union[str, None] = "12f0d22a2347"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ccdexposure_quicklook",
        sa.Column(
            "dummy_column1",
            sa.VARCHAR(length=64)
            .with_variant(mysql.VARCHAR(length=64), "mysql")
            .with_variant(sa.VARCHAR(length=64), "postgresql"),
            nullable=True,
            comment="Dummy column for testing.",
        ),
        schema="cdb_lsstcomcam",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ccdexposure_quicklook", "dummy_column1", schema="cdb_lsstcomcam")
    # ### end Alembic commands ###
