"""DM-9999992

Revision ID: 92ceb411a68f
Revises: 12f0d22a2347
Create Date: 2024-12-02 22:34:41.823191+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "92ceb411a68f"
down_revision: Union[str, None] = "12f0d22a2347"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ccdexposure_quicklook",
        sa.Column(
            "dummy_col2",
            sa.INTEGER().with_variant(mysql.INTEGER(), "mysql").with_variant(sa.INTEGER(), "postgresql"),
            nullable=True,
            comment="Dummy column 2.",
        ),
        schema="cdb_lsstcomcam",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ccdexposure_quicklook", "dummy_col2", schema="cdb_lsstcomcam")
    # ### end Alembic commands ###
